version: '2'

services:
  web-app:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/code
      - /code/node_modules